name: 05-1. GitHub Script - Thank you
on:
  issues: 
    types: [opened, edited, reopened, labeled]

# Limit the permissions of the GITHUB_TOKEN
permissions:
  contents: read
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thank you! We appreciate your contribution to this project.'
            })
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Training']
                  - name: Hello world
                    uses: actions/hello-world-javascript-action@v1
                    with:
                    who-to-greet: "${{ inputs.who-to-greet }}"
                    id: hello
                     - name: Echo the greeting's time
                       run: echo 'The time was ${{ steps.hello.outputs.time }}.'
                       shell: bash
                     })
